CREATE TABLE IF NOT EXISTS users
(
    user_id   bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    email     varchar(150) NOT NULL,
    user_name varchar(200) NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT unique_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items
(
    item_id      bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    item_name    varchar(100) NOT NULL,
    description  varchar(200) NOT NULL,
    is_available boolean      NOT NULL,
    user_id      bigint,
    request_id   bigint,
    CONSTRAINT items_pkey PRIMARY KEY (item_id),
    CONSTRAINT fk_owner
        FOREIGN KEY (user_id)
            REFERENCES users (user_id)
);